### ISSUE TITLE
Cistern : buggy planning

### ISSUE THREAD

**Issue by 40thoughts** [BenLubar/df-ai#10]
Hi,
It seems like there's a bug while building the cistern :
After channeling the the intermediate floors in the reservoir, the ai seems to plan stone block floor tiles on every open tile, so you end up with stone block floors on each previously dug tile, and then, the plugin plans to channel those tiles, which of course won't work because the floors are constructions.

Also, the dwarves tend to lose their picks in the stone stockpile (dump) outside next to the seed stockpile, then the picks are forbidden, while the stones aren't.

Anyways, thanks a lot for this plugin. I love the strategy you guys use to build your fortresses.

df-ai used on df linux 64-bits 43.05 (Ubuntu 16.4)

**Comment by BenLubar** [comment]
Just leaving this comment to help me with the release notes when the next version is ready:

- The well being "patched" is fixed by c508dd8c81d3146b5e6285fc03dda7168790b3f5
- The picks being forbidden is a side effect of how the dumping code works. I need to write some code that makes sure miners are never unassigned or given alternate jobs unless something catastrophic happens like the population of the fort going down to 1 dwarf. If the miners don't get unassigned, they won't drop their pickaxes, and the pickaxes won't be considered to be blocking the cistern from being ready.
