### ISSUE TITLE
Trading

### ISSUE THREAD

**Issue by dexofan23** [BenLubar/df-ai#30]
AI can't perform trade with latest Dev build, same as https://github.com/BenLubar/df-ai/issues/28
On Latest release it's work fine.

**Comment by lethosor** [comment]
If it's the same as #28, can you try what I suggested there instead of opening a new issue?

**Comment by lethosor** [comment]
Sorry, I didn't realize that issue was closed. Are you getting a confirmation dialog?

**Comment by dexofan23** [comment]
@lethosor nope. AI log that can not trade. Without confirmation window and without selecting any goods.

**Comment by dexofan23** [comment]
@lethosor nope. AI log that can not trade. Without confirmation window and without selecting any goods.

**Comment by BenLubar** [comment]
This was probably fixed by https://github.com/BenLubar/df-ai/commit/6e04942678478b6bd32463a06b3b93aa842da5f7 - the AI wasn't trading because it wasn't making any trade goods because it never tried to count corpses (and therefore never finished counting corpses) and the step where it decides what to build trade goods comes after that.

If this isn't fixed by build 171012001, re-open this issue or leave a comment.
