### ISSUE TITLE
Crashes and pauses with PeridexisErrant's Starter Pack 0.44.12-r02

### ISSUE THREAD

**Issue by Tracewyvern** [BenLubar/df-ai#48]
Seems to crash whenever attempting to create squads w/ DFHack 0.44.12-r1. Also, does not unpause game when units are starving.

0.44.12-alpha1 with DFHack 0.44.12-alpha1 does not have this problem.

**Comment by pyromartian** [comment]
I see the crash issue with creating squads, but my copy does unpause for starving units. It's not immediate but it unpauses after 2-3 seconds.

**Comment by mattregul** [comment]
I'm also crashing when creating new squads.  I'll seemingly happen randomly the start of a new game (within the first 10 minutes), or when new migrants arrive.

Everytime these are the last two lines of `df-ai.log`
`00005-04-28:0678 Creating new squad...`
`00005-04-28:0678 Selected uniform for squad: Metal armor`

**Comment by mattregul** [comment]
Using the nightly build from 7/17/18 (which includes your fix [53c812b]) seems to have fixed the crashing issue.

**Comment by BenLubar** [comment]
Yeah, the crash is specifically because of what happens when it tries to create a new squad and then use the new squad without remembering that it didn't have a squad selected before.

I've also fixed a huge problem with the new version of the exclusive callback system where "wait 1 frame" would actually wait 0 frames.
