### ISSUE TITLE
Rooms not being dug

### ISSUE THREAD

**Issue by ZyroFalcon** [BenLubar/df-ai#6]
1 - http://i.imgur.com/KDdfSq1.png
2 - http://i.imgur.com/vMtmfgy.png
Maybe it's because of the smoothed, carved walls? v('_')v
Also is it okay that my ai fort does not do trade import agreements?
![todigornottodig](https://cloud.githubusercontent.com/assets/11038747/17121671/e2465bf2-5307-11e6-8f90-f1639ec23428.png)
![todigornottodig2](https://cloud.githubusercontent.com/assets/11038747/17121678/e6c8b166-5307-11e6-8dd6-93e152947bb0.png)

**Comment by BenLubar** [comment]
Weird, the logs in your first screenshot say that it's digging the mayor's office (which is the room on the far left at the top) but the room is already fully furnished and there are no "furnish [furniture type] in [room description]" messages. Plus, it says the room is in plan mode, which can only happen when it hasn't been connected to the hallway yet through designations, and there's no digroom message between there and the end of the log.

:/

**Comment by BenLubar** [comment]
> Also is it okay that my ai fort does not do trade import agreements?

Yeah, the AI doesn't do trading yet so it just quits out of those screens.

**Comment by ZyroFalcon** [comment]
Say, do you think my clicking on the screen to look at stuff's details could've interfered with DF-AI?
What about when I pressed Esc to save and quit DF, then started up DF another time to resume the save?
DF-AI is new to me (as I am new to Dwarf Fortress as a whole).

**Comment by BenLubar** [comment]
> Say, do you think my clicking on the screen to look at stuff's details could've interfered with DF-AI?

Clicking may have done something if it was using keyboard commands to designate the room and you just happened to have clicked on the frame that it was going to designate stuff. I'll have to make it more resilient against being interrupted, so it retries if the game isn't where it wants it. It shouldn't cause the room to be (plan) still, though, so I don't think that's it.

> What about when I pressed Esc to save and quit DF, then started up DF another time to resume the save?
> DF-AI is new to me (as I am new to Dwarf Fortress as a whole).

Saving and loading might have been the problem if I messed something up in my save-load code.

> Edit: Oh, btw, I started a new world and the dwarves are digging the rooms normally as expected. Hmm... Let's hope this is only a fleeting, rare issue?

The good news: If you didn't see the issue again on a new world, it's probably not something that happens commonly.
The bad news: If the bug is hard to reproduce, it's hard to fix.

> Edit 2: The dwarves of this new world seem to prefer sleeping wherever, rather than in their beds :I

If it still has undug or unfurnished bedrooms, it might just be that the bedrooms the AI assigned were chosen by dwarves other than the ones you saw sleeping on the floor.

**Comment by BenLubar** [comment]
Ok, this might be fixed by 0260b7e8219126a7ad2df0b7f4e0e0fa938c9a2e - a bunch of stuff that isn't strictly part of the fortress was being put into the same queue as the interior of the fortress. The next version of the AI will ignore cavern exploration and mining when deciding whether it should dig the next room, and it uses mark-designations (blue) instead of normal designations (yellow) when the room is planned but not ready to dig, so it should be a bit easier to see what it's thinking.
